language: node_js
node_js:
  - "9"
cache:
  directories:
  - node_modules
script:
  - npm run travis
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $github_token
  local_dir: build/public # for github pages
  on:
    branch: master
