apiVersion: v1
kind: Service
metadata:
  name: default-backend
  namespace: ingress
spec:
  type: ClusterIP
  selector:
    name: default-backend
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
