apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ingress
  namespace: ingress
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ingress
subjects:
  - kind: ServiceAccount
    namespace: ingress
    name: default
