apiVersion: v1
kind: Service
metadata:
  name: grafana
  namespace: monitoring
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '8080'
spec:
  type: ClusterIP
  selector:
    name: grafana
    phase: prod
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
