apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: heapster
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: system:pod-nanny
subjects:
- kind: ServiceAccount
  name: heapster
  namespace: kube-system
